### ISSUE TITLE
Cannot conenct to socket after moving.

### ISSUE THREAD

**Issue by Nekroze** [moul/docker-drupal#1]
Heyo Moul,

Good work on this image however i am having one issue. Currently i store all of my data for my drupal containers outside of a docker container using a volume to `/data` as you have setup.

This works great for re-creating the containers, however, for some reason when i move the data to a new computer and run a new drupal container using that image i get the following error:

![drupal](https://f.cloud.github.com/assets/1460186/2404135/8403f7f0-aa37-11e3-95d3-d4e09f7d461b.PNG)

The only solution i have found is to delete my data and start again, at this point that is not an issue but perhaps in the future it will be.

**Comment by Nekroze** [comment]
This could be a terrible idea but maybe make `/var/run/mysqld/` a volume so that we can have that persist aswell. Just an untested thought.

**Comment by moul** [comment]
Hi @Nekroze,

I didn't see your issue earlier, I imagine it's now too late and you found a better solution, but in case it may help you or somebody else:

I have no idea why moving your data get this problem, I already moved data from a server to another without issue, do you think something may have changed during the moving process ? i.e. permissions changed, file ownership changed ?
Did you stopped the docker image before moving the data or was it a "hot" migration ?

**Comment by Nekroze** [comment]
Hi @moul 

So sorry for necroing this issue, I was playing around with octodroid on my phone :yum: 

I believe at the time I just deleted the db and restarted it. I like to think I would have checked the permissions and stoped the containers.

Feel free to close this off as I have little information left about this.

**Comment by moul** [comment]
ok no problem, :)
